version: "4.0"

services:

  mysql:
    image: mariadb
    container_name: mysql
    hostname: mysql
    restart: unless-stopped


  glpi:
    image: dunvael/glpi_v10.0.9
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    
    
