version: "4.0"

services:

  mysql:
    image: mariadb
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: unless-stopped


  glpi:
    image: dunvael/glpi_v10.0.9
    container_name : glpi
    hostname: glpi
    ports:
      - "5001:80"
      - "5002:443"
    volumes:
      - ./glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Santiago
    restart: unless-stopped
    
    
